name: PR First Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for creating an issue! Our maintainers will look into this as soon as possible."
        pr-message: "You're just a few steps away from getting a new subdomain!\nPlease double check that you have followed the format found [here](https://docs.is-a-good.dev/format).\nOnce everything checks out, the maintainers will merge this PR and you should be good to go!"
